Tippfehler Korrektur 1 (19.04.2017)
hd-notes/notes pull request #17
Opened 2017-04-19 17:25 UTC by ddrrhh

Einige Tippfehler für Dich

2017-04-20 15:11 UTC, rroohhh requested changes

2017-04-20 15:11 UTC, rroohhh commented on ipi/procedural_programming.org
> -	  \[x^{(t + 1)} = x^{(t)} - \frac{f(x^{(\ast)})}{f'(x^{(\ast)})}\]
Die Zahlen sollen hier im Exponenten bleiben

2017-04-20 15:11 UTC, rroohhh commented on ipi/substitution_model.org
> -   1. <<algstart1>> Wenn die Wurzel ein Blatt ist: Drucke die Zahl
Das hier ist eigentlich garnicht doppelt, nur der Titel ist falsch

2017-04-20 15:13 UTC, rroohhh commented
Könntest du bitte die den merge conflict beheben?

2017-04-21 07:07 UTC, ddrrhh commented
Habe ich!

> Am 20.04.2017 um 17:13 schrieb Robin Heinemann <notifications@github.com>:
> 
> Könntest du bitte die den merge conflict beheben?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/hd-notes/notes/pull/17#issuecomment-295773278>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AWRmHwOEc3hs_Pp_z5yp9X-SD7CRCKmGks5rx3YFgaJpZM4NB_kd>.
>

2017-04-21 10:07 UTC, ddrrhh commented
Habe alles gefit

2017-04-21 10:37 UTC, merged

2017-04-21 10:37 UTC, rroohhh commented
Super, danke