Korrekturen von 10.05.2017
hd-notes/notes pull request #20
Opened 2017-05-10 17:51 UTC by ddrrhh

2017-05-10 21:05 UTC, rroohhh requested changes

2017-05-10 21:05 UTC, rroohhh commented on ana2/differentiation.org
> +     \[f(x_ε) = \frac{ε^2}{4 ε^4} = \frac{1}{4 ε2} \xrightarrow{ε \to 0} ∞\]
Das müsste Quadrat sein

2017-05-11 04:37 UTC, ddrrhh commented
Habe ^2 Fehler in ana2/differentiation.org korrigiert. 
Irgendwie hatte der Editor Probleme Probleme das "^" anzunehmen. 
Heute morgen habe ich auch zwei versuche gebraucht.

2017-05-12 08:49 UTC, rroohhh approved these changes

2017-05-12 08:49 UTC, merged